### ISSUE TITLE
filter out all items in the step "Filter down to catholic and public school students and create a  dummy for catholic"

### ISSUE THREAD

**Issue by WhitePredator** [sejdemyr/ecls#1] opened 2018-07-04 01:40 UTC
Hi!
thanks for your share for the data and the propensity score tutorial.

when i run the R scrip, after the step "Filter down to catholic and public school students and create a  dummy for catholic", no items exist at all in "dta", i am not familar to the data stucture and do not know what happened, would you help?

thanks!

**Comment by WhitePredator** [comment] 2018-07-04 02:32
finally i solved it,  change the  code "filter(l5cathol == 'YES' | l5public == 'YES')"  to "filter(l5cathol == '1' | l5public == '1')"

**Comment by WhitePredator** [comment] 2018-07-04 03:32
another quetion: the "r5race" is " "1"  "3"  "8"  "7"  "2"  "5"  "6"  "4"  "-9"",not "white" ,"black"....
so where can i find what the number of "r5race" represent?

**Comment by sejdemyr** [comment] 2018-07-04 19:41
Thanks for reporting this issue! The best fix here would be to use something other than the SPSS-compatible data from ECLS (I'm not a huge fan of `spss.get()`, which very well might be the cause of this issue). For example, there's a .txt file in the Stata-compatible download. Feel free to try that .txt file instead, and if you can't get that to work I'll try to do it myself in the next couple of days :)

**Comment by WhitePredator** [comment] 2018-07-06 08:29
I tried the stata data, but did not find a proper way to imported in R. Then I tried the sas data, using the function "foreign::read.xport"  to import data. However, the issue I described above still exist.

**Comment by sejdemyr** [comment] 2018-07-20 04:29
@WhitePredator - the issue has been resolved by using `read_por()` from `haven` to read the data.

**Closed as completed by sejdemyr** 2018-07-20 04:29 UTC
